services:
  - type: web
    name: tour-recommendation-api
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /v3/api-docs
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: FILE_BASE_URL
        value: https://tour-recomendation-backend.onrender.com/uploads
