spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

google.client-id=${GOOGLE_CLIENT_ID}

file.upload-dir=${FILE_UPLOAD_DIR:uploads}
file.base-url=${FILE_BASE_URL}
